services:
  oauth2smtp:
    image: ghcr.io/wlnxing/oauth2smtp:latest
    container_name: oauth2smtp
    restart: always
    ports:
      - "2525:2525"
    volumes:
      - ./config.yaml:/config/config.yaml:rw
